name: 'Builder'

on:
  schedule:
    # 19:00 GMT (00:00 UTC+5)
    - cron: '0 19 * * *'
  workflow_dispatch:
    inputs:
      timezone:
        description: Timezone
        default: Asia/Yekaterinburg

env:
  output: build
  FORCE_COLOR: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Set Timezone
      uses: digipost/set-timezone@v3
      with:
        timezoneLinux: ${{ inputs.timezone }}

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Build
      continue-on-error: true
      run: python -u src/main.py -vfH -o "${{ env.output }}"

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ env.output }}
        retention-days: 7

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
