name: 'Builder'

on:
  # push:
  #   branches:
  #   - master
  schedule:
    # 19:00 GMT (00:00 UTC+5)
    - cron: '0 19 * * *'
  workflow_dispatch:
    inputs:
      output_dir:
        description: 'Output directory'
      timezone:
        description: 'Timezone'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Initiate variables
      run: |
        cat << EOF >> $GITHUB_ENV
        DATE=$(date +'%d-%m-%Y')
        OUTPUT_DIR=$([ -z $OUTPUT_DIR ] && echo "${{ secrets.OUTPUT_DIR }}" | base64 -d || echo ${{ github.event.inputs.output_dir }})
        TIMEZONE=$([ -z $TIMEZONE ] && echo "${{ secrets.TIMEZONE }}" | base64 -d || echo ${{ github.event.inputs.timezone }})
        EOF

    - name: Set timezone
      uses: digipost/set-timezone@v3
      with:
        timezoneLinux: ${{ env.TIMEZONE }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build a repo
      continue-on-error: true
      run: NO_COLOR=1 python -u src/main.py -vfH -o ${{ env.OUTPUT_DIR }}

    - name: Upload a named artifact
      uses: actions/upload-artifact@v4
      with:
        name: ddrg_${{ env.DATE }}
        path: ${{ env.OUTPUT_DIR }}
        retention-days: 90

    - name: Upload an artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.OUTPUT_DIR }}
        retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:

    - name: Deploy the repo to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
