name: 'repository-builder'

on:
  workflow_dispatch:
    inputs:
      selected_distros:
        description: 'Selected distros'
        default: 'all'
        required: true
      output_dir:
        description: 'Output directory'
        default: 'repo'
        required: true
      timezone:
        description: 'Timezone'
        default: 'Asia/Yekaterinburg'
        required: true
  push:
    branches:
    - master

env:
  OUTPUT_DIR: ${{ github.event.inputs.output_dir }}
  SELECTED_DISTROS: ${{ github.event.inputs.selected_distros }}
  TIMEZONE: ${{ github.event.inputs.timezone }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: ${{ env.TIMEZONE }}

    - name: Install packages
      run: pip install -r requirements.txt

    - name: Build repository
      continue-on-error: true
      run: python -u src/main.py -g -o ${{ env.OUTPUT_DIR }} -d ${{ env.SELECTED_DISTROS }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.OUTPUT_DIR }}
        path: ${{ env.OUTPUT_DIR }}

    - name: Deploy website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: website
        publish_dir: ${{ env.OUTPUT_DIR }}
        cname: ${{ secrets.CNAME }}
        force_orphan: true

    - name: Deploy website to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: ${{ env.OUTPUT_DIR }}
        target: ${{ secrets.SSH_DIR }}
        strip_components: 1
        rm: true
